export interface User {
  // User data to send on frontend
  id: string;
  username: string;
  email: string;
  role: "captain" | "analyst";
  created_at?: number; // Automatically generated by my sql
}

export interface IUser extends User {
  // User data to validate and send to sql database
  password: string;
}

export interface Vessel {
  id: string;
  name: string;
  imo_number: number;
  captain_id: string | null;
  created_at: Date;
}

export type VoyageStatus = "planned" | "active" | "completed";

export interface Waypoint {
  latitude: number;
  longitude: number;
  name?: string;
  order: number;
}

export interface Voyage {
  id: string;
  vessel_id: string;
  status: VoyageStatus;
  origin_port: string;
  destination_port: string;
  etd: Date | null;
  eta: Date | null;
  route_waypoints: Waypoint[] | null;
  created_at: Date;
}

export interface VoyageWithVessel extends Voyage {
  vessel_name?: string;
  vessel_imo_number?: number;
}

export interface WeatherData {
  temperature: number;
  humidity: number;
  windSpeed: number;
  windDirection: number;
  pressure: number;
  visibility: number;
  cloudCover: number;
  precipitation: number;
  weatherCode: number;
  timestamp: number;
  location: {
    lat: number;
    lon: number;
  };
}

export interface ForecastData {
  daily: WeatherData[];
  location: {
    lat: number;
    lon: number;
  };
}

export interface SpeedRecommendation {
  optimalSpeed: number;
  maxSafeSpeed: number;
  weatherFactors: {
    windSpeedFactor: number;
    visibilityFactor: number;
    precipitationFactor: number;
    waveFactor?: number;
  };
  riskLevel: "LOW" | "MEDIUM" | "HIGH" | "EXTREME";
  recommendations: string[];
}

export interface UpdateLocationData {
  captainId: string;
  lat: number;
  lon: number;
  voyage_id: string;
}

// Enhanced alert severity levels with priority
export type AlertSeverity = "info" | "warning" | "critical" | "emergency";

export interface AlertData {
  id: string;
  voyage_id: string;
  alert_type: string;
  message: string;
  severity: "info" | "warning" | "critical" | "emergency";
}

export interface AlertRules {
  type: string;
  severity: AlertSeverity;
  priority: number; // 1 = highest, 5 = lowest
  category:
    | "wind"
    | "visibility"
    | "precipitation"
    | "marine"
    | "temperature"
    | "pressure"
    | "cyclone";
  check: (data: WeatherData, forecast?: ForecastData) => boolean;
  message: (data: WeatherData, forecast?: ForecastData) => string;
  recommendations?: string[];
  debounceTime?: number; // minutes to wait before sending same alert type again
}
