export interface User {
  // User data to send on frontend
  id: string;
  username: string;
  email: string;
  role: "captain" | "analyst";
  created_at?: number; // Automatically generated by my sql
}

export interface IUser extends User {
  // User data to validate and send to sql database
  password: string;
}

export interface Vessel {
  id: string;
  name: string;
  imo_number: number;
  captain_id: string | null;
  created_at: Date;
}
